# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6afab599b42f46dd272442283ede53017f2f6687f03824414942e023acec2e86efa501ac6ce6c0bdc27a0a23dd4248a64835784ced567e6fb443ceac4b475d3c

test:
  secret_key_base: a2e037be104d9b2415c4a12ffb2c2685afabda4534f2967354023b4b3908d0ecdf2886e7334684b76f0cd4e811aef5cf00785391875133872da65254d51f78c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
